# Generated by Django 5.1.1 on 2024-10-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="taking",
            new_name="takings",
        ),
        migrations.AddField(
            model_name="course",
            name="course_semester",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_year",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
