# Generated by Django 5.1.1 on 2024-10-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0003_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
