# Generated by Django 5.1.1 on 2024-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0005_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="taking",
            name="status",
            field=models.CharField(default="Open", max_length=5),
            preserve_default=False,
        ),
    ]
