# Generated by Django 5.1.1 on 2024-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0006_taking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.CharField(max_length=5)),
            ],
        ),
    ]
